f1=open("file1.txt","w")
f1.write("Swadhin")
f1.write("python file")
f1.close()
f1=open("file1.txt","r")
f2=open("file2.txt","w")
data=f1.read()
f2.write(data)
print("Data copied from file1 to file2")
f1.close()
f2.close()  